name: build-test

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: ['16']
    steps:
      - uses: actions/chekout@v2
      - name: Setup Node 16
        uses: actions/stup-node@v2
        with:
          node-version: 16.x
      - run: run npm install
      - run: npm run lint
